// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddfskfebaewssdwpzxjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZnNrZmViYWV3c3Nkd3B6eGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MzgyNDYsImV4cCI6MjA1NDUxNDI0Nn0.1cFYwXIK9bgPR5AK3c4YP--1nBxGcTBaBYLaKR1O_OE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);